### ISSUE TITLE
versions.tf in the module is referring to wrong path of newrelic provider

### ISSUE THREAD

**Issue by Nagarajantv** [newrelic/terraform-newrelic-apm#11]
https://github.com/newrelic/terraform-newrelic-apm/blob/e324b4e2445fc74a3633e0d281a14cca2f753ddc/versions.tf#L4-L6

The above code in versions.tf is referring to newrelic provider source 'registry.terraform.io/**hashicorp/newrelic**' which doesn't exist. Hence while trying to execute 'terraform init' we are getting the below error:

```
Initializing provider plugins...
- Finding latest version of hashicorp/newrelic...
- Reusing previous version of newrelic/newrelic from the dependency lock file
- Using previously-installed newrelic/newrelic v2.49.1
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/newrelic: provider registry registry.terraform.io does not have a provider named
│ registry.terraform.io/hashicorp/newrelic
│
│ Did you intend to use newrelic/newrelic? If so, you must specify that source address in each module which requires that provider. To see which modules are currently  
│ depending on hashicorp/newrelic, run the following command:
│     terraform providers
```

To resolve this error, under the required_providers section, newrelic provider source should be referred as '**newrelic/newrelic**' similar to the one in the terraform registry documentation under 'Use Provider' section - https://registry.terraform.io/providers/newrelic/newrelic/2.49.1

Corrected versions.tf

```
terraform {
  required_version = ">= 0.12.6"

  required_providers {
    newrelic = {
      source  = "newrelic/newrelic"
      version = "~> 2.21"
    }
  }
}
```

Raised pull-request #10 to update versions.tf by including the above suggestions.

**Comment by kidk** [comment]
Fixed with #10
