### ISSUE TITLE
Module in the terraform registry is still pointing to the older version of the code

### ISSUE THREAD

**Issue by Nagarajantv** [newrelic/terraform-newrelic-apm#12]
Recently there was pull request #10 to fix the versions.tf file to correct the provider path. We could see that the PR has been merged in the github, but the module in the terraform registry is still pointing to the old version of code(Version 0.0.5 - Published in July,2020)

Can you publish the latest version of module to the Terraform registry?

**Comment by kidk** [comment]
Fixed https://registry.terraform.io/modules/newrelic/apm/newrelic/0.0.6
